package com.lida.dream_webservice.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-18T12:07:59.829+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "MyWebserviceImplService", 
                  wsdlLocation = "http://localhost:8080/server//web-publish?wsdl",
                  targetNamespace = "http://server.dream_webservice.lida.com/") 
public class MyWebserviceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.dream_webservice.lida.com/", "MyWebserviceImplService");
    public final static QName MyWebserviceImplPort = new QName("http://server.dream_webservice.lida.com/", "MyWebserviceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/server//web-publish?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyWebserviceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/server//web-publish?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebserviceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MyWebserviceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyWebserviceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebserviceImplPort")
    public MyWebService getMyWebserviceImplPort() {
        return super.getPort(MyWebserviceImplPort, MyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebserviceImplPort")
    public MyWebService getMyWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(MyWebserviceImplPort, MyWebService.class, features);
    }

}
